import Head from "next/head";

export default function Female(props) {

    console.log(props)
    return (
        <div>
            <Head>
                <title> Female</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Address Book</h1>
                <h3>Hello Terry!</h3>
                <table>
                    <tr>
                        <th>Avatar</th>
                        <th>Name</th>
                        <th>Email</th>
                    </tr>
                    {/*{list?.map((row , i)=>*/}
                    {/*    <tr key={i}>*/}
                    {/*        <td><img src={row.picture.thumbnail} alt={row.name?.first}/></td>*/}
                    {/*        <td>{`${row.name?.title} ${row.name?.first} ${row.name?.last}  `}</td>*/}
                    {/*        <td>{row.email}</td>*/}
                    {/*    </tr>*/}
                    {/*)}*/}
                </table>

            </main>

        </div>
    )
}